### PR TITLE
DOCS-2225 (vCenter Plugin): Document Fibre Channel options in Datastore article

### PR DESCRIPTION
**Pull request by tonyriv3**

### CODE REVIEW

**Comment by tonyriv3** [comment]
I added Fibre Channel option details and did a technical writer review.

**Comment by Mrt134** [comment]
pinging @ZackaryWelch for a review - can't seem to add to reviewer list for some reason.

**Review by BonnieF — CHANGES_REQUESTED** [review]
In the sentence" Select the datastore VMFS Version from the drop-down menu. Choose between the modern version 6 or the legacy versions 3 and 5. See the VMware VMFS documentation for detailed comparisons."
 the VMware VMFS documentation leads to a page that says "Oops!
We’re sorry. We couldn’t find any results for keyword(s)"

Fibre Channel port need to be italicized

The NAS has to have a Fibre Channel  license.

So maybe something like:
To utilize Fibre Channel ports your high availability NAS has to to include a Fibre Channel license. Fibre Channel HBAs and a network set up are a pre-requisite to setting up a Fibre Channel fabric with the NAS and ESXi. You will be able to select a Fibre Channel port for the datastore.

**Comment by tonyriv3** [comment]
@BonnieF 
Thanks for checking that link! That's something a need to remember to do when I'm reviewing older articles.

I slightly reworded the Fibre Channel port section to include licensing.

**Review by BonnieF — APPROVED** [review]

**Comment by Mrt134** [comment]
Marking as Work in Progress and holding merge until Plugin 3.4.0 is released.

**Comment by Mrt134** [comment]
Comment from @ZackaryWelch : We might should add a note mentioning rollback will fail for FC datastores, so the user will have to delete those manually on failure.
https://jira.ixsystems.com/browse/VCP-135

**Pull request merged**
