### PR TITLE
PD-370 Update Storj Content

### PR DESCRIPTION
**Pull request by micjohnson777**
This commit updates the content with suggested changes made in the PR review. PR was merged too soon and before technical review. This PR makes changes to that content.

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by micjohnson777** [comment]
Added both Rehan and Stavros to provide a technical review of the changes requested by Morgan and verify the instructions provided in this PR are correct.

**Comment by RehanY147** [comment]
I think I was asked for a review by mistake. I've tagged my namesake from the middleware team for a review. If I was not tagged by mistake, please let me know.

**Comment by micjohnson777** [comment]
I tagged you for a technical review of the content to make sure I have this
correct. We talked about it in a DM.

**Comment by stavros-k** [comment]
I don't see anything wrong!

Just an addition, if the identity is not present on the storage directory, it will generate and authorize one automatically.
But keep in mind that this can take **long** time and consume resources of the system while generating one.

**Comment by Mrt134** [comment]
@micjohnson777 there are a number of conflicts to review and make sure the correct content is merging in to master.

**Comment by micjohnson777** [comment]
Conflicts finally resolved but some feedback comments/commits might be lost. This needs the once-over again.

**Review by Mrt134 — APPROVED** [review]

**Pull request merged**
