### PR TITLE
(TC2) DOCS-1950: Alert Management content updates

### PR DESCRIPTION
**Pull request by q5sys**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by q5sys** [comment]
This needs the email/pagerduty sections reworked and approved by Ken/Tim.  Do not merge this PR until that is done.

**Comment by Mrt134** [comment]
tab boxes approach looks to be appropriate in this case - added Ken for technical review

**Comment by beanpole135** [comment]
Looks fine to me from a technical perspective.

**Review by ericbsd — APPROVED** [review]
LGTM

**Comment by Mrt134** [comment]
zsh.org is down right now, no other issues seen from the build test

**Pull request merged**
