### PR TITLE
(TC2) DOCS-1944: Single system management topic

### PR DESCRIPTION
**Pull request by tonyriv3**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Review by BonnieF — APPROVED** [review]

**Comment by Mrt134** [comment]
To maintain linearity, this PR needs to be merged after #852

**Comment by Mrt134** [comment]
Related PR is merged, this one can get merge conflicts resolved, reviewed, and merged now

**Review by Mrt134 — COMMENTED** [review]
The new file names need to have the extra whitespaces removed.
The _index.md file needs to be the same weight as the file it is replacing.
"TrueCommand" is camel-cased (check the article titles)
Articles within the new topic need their weights adjusted to 10, 20, and 30, depending on which article should be seen first (follow the UI flow as closely as possible)

**Comment by tonyriv3** [comment]
Thanks for the review, @Mrt134! This is my first time adding brand new stuff since Docs 2.0. The little stuff sneaked by me.

**Review by BonnieF — APPROVED** [review]

**Pull request merged**
