### PR TITLE
Use fixed dataset name in Sandboxes setup

### PR DESCRIPTION
**Pull request by Jip-Hop**
See https://github.com/Jip-Hop/jailmaker/issues/107

Can this also please be 'backported' to 24.4 so these changes will show up at the link below?
https://www.truenas.com/docs/scale/24.04/scaletutorials/apps/sandboxes/

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by DjP-iX** [comment]
Thank you for this contribution @Jip-Hop! I agree that changing the first suggestion of `*sandboxes* or *jails*` to a single, consistent term would help avoid confusion. However I think it is better to settle on consistently using the feature name *sandboxes* rather than changing all references to *jailmaker*, which is an external project. Using that name in this context would be more likely to increase confusion than decrease it.

**Comment by Jip-Hop** [comment]
Thanks for replying @DjP-iX. Jailmaker is indeed an external project, of which I am the author. This docs page describes the process of setting up jailmaker. In the linked issue you can read that jailmaker doesn't work as expected when the dataset is not named "jailmaker". Therefore it's not only less confusing, the current instructions are unfortunately not correct. Can you please approve this PR?

**Comment by DjP-iX** [comment]
Ah I misunderstood the issue there. Since jailmaker is presented in the tutorial as a possible use but not the only use case for sandboxes, I'd lean toward leaving a generic name in the tutorial then also explaining (possiblly in an admonition) that the dataset should be named jailmaker if using it.

**Comment by Jip-Hop** [comment]
I don't see it that way. The only thing being described on that page is how to setup jailmaker. Currently TrueNAS doesn't offer a way to create and manage sandboxes. There's only jailmaker. There's no point in confusing the reader, by making the instructions more generic, by covering something which doesn't yet exist. If in the future TrueNAS would have a way to create and manage sandboxes, then I expect the implementation to be different from the one I came up with for jailmaker. By then, it would make sense for users to perhaps create a new, dedicated, dataset for sandboxes with an appropriate name. But for now, people who use jailmaker should have a dataset called "jailmaker" and it would be helpful if this is reflected in the manual.

**Comment by Jip-Hop** [comment]
When I follow the instructions as they are currently written, jailmaker will exit with the following error when creating a jail:

```
root@scale:/mnt/tank/sandboxes# ./jlmkr.py create
USE THIS SCRIPT AT YOUR OWN RISK!
IT COMES WITHOUT WARRANTY AND IS NOT SUPPORTED BY IXSYSTEMS.

jlmkr.py needs to create files.
Currently it can not decide if it is safe to create files in:
/mnt/tank/sandboxes
Please create a dedicated directory called 'jailmaker', store jlmkr.py there and try again.
```

I should have more carefully reviewed these docs when @kmoore134 asked me to. I see the screenshots need updating as well... which I didn't do in this PR.

**Comment by kmoore134** [comment]
Yea, we will approve this, since if the instructions don't work today as given we need to resolve that :)

**Review by kmoore134 — DISMISSED** [review]

**Review by Jip-Hop — COMMENTED** [review]
Thanks for updating the screenshots! :)

**Review by Mrt134 — APPROVED** [review]

**Pull request merged**
