### PR TITLE
Docs 3060 Publish SCALE 2 FA Video

### PR DESCRIPTION
**Pull request by micjohnson777**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Review by BonnieF — CHANGES_REQUESTED** [review]
Did we do that video? It is a minor thing but the video shows the user clicking Save before enabling 2FA. It didn't show them clicking the Save button after changing the settings.

**Comment by micjohnson777** [comment]
Bonnie, That was done by Barak our contractor that is now a Support employee. I guess we'll need to discuss with Tim if we want him to fix it or if we want to try to fix it in house. Is this enough to block the article?

**Comment by Mrt134** [comment]
That's a continuity error that we can correct when we begin creating and maintaining more videos in-house (hint hint). Let's not block this merge based on that.

**Review by BonnieF — APPROVED** [review]
I will check with Tim about the video but it's not a reason to stop this merge.

**Pull request merged**
