### PR TITLE
whitelist external github link

### PR DESCRIPTION
**Pull request by q5sys**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Review by Mrt134 — COMMENTED** [review]
Instead of doing it this way, can we exclude the entire themes/ directory from the link check? That isn't included when building and won't affect the final site. In general, I'm keeping the themes/ dir "off-limits" to all changes that aren't generated by the upstream theme owner.

**Comment by q5sys** [comment]
> Instead of doing it this way, can we exclude the entire themes/ directory from the link check? That isn't included when building and won't affect the final site. In general, I'm keeping the themes/ dir "off-limits" to all changes that aren't generated by the upstream theme owner.

You can select what dir the linker checks, but I dont think you can whitelist an entire dir.
however if you want, I can whitelist all github.com links... that should cover everything in the theme stuff that might creep in over time.

**Comment by Mrt134** [comment]
the docshubtwo branch needs to be reworked with the final github actions before anything related to this can be merged. I'll come back to this next week.

**Review by Mrt134 — DISMISSED** [review]
Double checked the actions configurations: the daily link check only reviews files inside the content/ directory and the PR checker only reviews files modified in the PR. We should not need to whitelist anything in the themes/ directory.

**Comment by Mrt134** [comment]
PR check is functioning well enough for now, we'll be resolving dead links in a separate review after most of the content ports are complete.

**Review by Mrt134 — APPROVED** [review]

**Pull request merged**
