### PR TITLE
PD-834: website refresh

### PR DESCRIPTION
**Pull request by Mrt134**
**Changelog**
Updates:
- Review website CSS and update a number of color values to use variables correctly and be less "heavy" to readers in either light or dark mode viewing.
- Fix a bug with the top menubar widths
- Update footer spacing to allow for the reCaptcha element.
- Small screen & mobile friendly review pass with small updates to ensure good visibility and usability for different screen sizes.
- Update left side sitenav to be lighter weight font and remain in position while the main content panel scrolls. Also remove title as unnecessary.
- Experiment with a couple content reworks of SCALE CLI Reference Guide content files (auth and network). These are intended as simple examples of different ways to document these spaces.

New: 
- **AutoTOC**: Right side element that autopopulates with links to the various headers within a content article. On large screens, this panel is hidden when there are only two headers or less. Small/mobile screens have a toggle button to make the panel visible on the right side of the screen when desired. This element is sticky and remains in view while the content scrolls.

- **Expand Rework**: replace all existing styling and behavior for expand and nest-expand shortcodes. Now expandable elements are built with an HTML details element that allows for lighter intrusion into content and full support for browser Control + F searching. Expands can be automatically toggled by searches and anchor scrollto behaviors as well. This rework is functional with all existing expand and nest-expand shortcodes; no content changes should be necessary.

- **cli shortcode**: this new shortcode wraps around inline command examples to apply some inline styles and a copy button that copies the text string to the local system clipboard when pressed. This is intended for use only when writing specific cli commands or elements that the text is useful/functional when copied. Example: {{< cli >}}ifconfig{{< /cli >}}.
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Review by micjohnson777 — COMMENTED** [review]
Found some issues:
Tables
- If in the Enterprise shortcode, and you switch to dark mode with the sun/moon icon, the text doesn't switch to light so you can't read the text in the dark rows.
- Hover over a table row makes the dark row even darker.

Hint boxes,
- do we need the darker title/header color? this adds to the boxy look especially if you have Enterprise and hint boxes stacked like we do in the Getting Started section. Can we work to using different icons for  each type and use a light border and do away with the colors completely?

Left nav
- cuts off the list so you can't see all the articles, for example, Tutorials for System Settings only shows two of the seven options so you can't get to General or Advanced setting options. This is the same in all books.

Snippets
- Expands don't indent properly.
- Step list with bullets under it don't indent properly so they break the flow of the step procedure.
- Expands with indented bullet lists under steps incorrectly align with the step and are not indented when they should.
- in the firstTimeLogin.md snippet, the list of expand have wonky spacing between expand.

Expands (not in snippets)
- need more space before/after the open and close shortcodes so the content is not bunch up under the expand title, or on top of the next expand.

Nested Expands
- do not indent properly when they should they don't.

Code emphasis
- not all code-formatted text should have the copy to clipboard.  The icon obscures text following it if it is used in a paragraph.
- We should have one shortcode to create a copy to clipboard option.

**Comment by Mrt134** [comment]
@micjohnson777 all feedback has been addressed (sans CTA/footer elements resolved elsewhere) with the latest commits.

**Comment by micjohnson777** [comment]
Spot check of links and functions looks good, and they appear to work correctly. The left nav scroll bar is nice as is the change to the expand!!

**Review by micjohnson777 — APPROVED** [review]

**Comment by micjohnson777** [comment]
PR is approved but has conflicts with CLI content that must be resolved

**Review by micjohnson777 — APPROVED** [review]

**Pull request merged**
