### PR TITLE
Adjust RSS feed to use permalinks.

### PR DESCRIPTION
**Pull request by Mrt134**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by rapperskull** [comment]
The link on line 12 should be also changed

**Comment by Mrt134** [comment]
Got it, thanks!

**Comment by rapperskull** [comment]
I can confirm Thunderbird no longer complains

**Review by ericbsd — APPROVED** [review]
LGTM

**Pull request merged**
