### PR TITLE
NAS-110169 [SCALE] PVC datasets not accessable from folder

### PR DESCRIPTION
**Pull request by tonyriv3**

### CODE REVIEW

**Comment by Ornias1993** [comment]
I think this is a rather crude and unhelpfull description, considering this isn't helping users that actually need to access PVC data (for example for data recovery or migration purposes).

THe correct workflow would be (in short):
- Stop App
- Mount Dataset to a folder
 _do what you need to do_
- Set mount back to "legacy"
- start App again.

This could even be automated with relative ease.

**Comment by sonicaj** [comment]
@Ornias1993 we do not want users to manually edit mountpoints to perform various tasks. This can be easily done via pod and that's how it should be ideally as well. So users can either mount the host path inside the pod and the PV and then copy/move data accordingly or they can just use the network to copy it over which is how it would normally work with a k8s cluster. That said we can document that PV's can be accessed via the pod, thanks!

**Comment by sonicaj** [comment]
https://medium.com/@nnilesh7756/copy-directories-and-files-to-and-from-kubernetes-container-pod-19612fa74660

**Comment by Ornias1993** [comment]
@sonicaj To be fair, thats why I didn't document "my" method for TrueCharts either, because I knew there should've been a " cleaner" solution.
Yours seems to be just about precisely what I think should be documented indeed and should cause a lot less user error than mounting and unmounting datasets :)

**Pull request closed without merging**
