### PR TITLE
removing broken link

### PR DESCRIPTION
**Pull request by g33z**
The proposed anchor link was not relating to any existing headline / anchor.
It's this page, btw: https://www.truenas.com/docs/scale/gettingstarted/migrate/migratingfromcore

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Comment by g33z** [comment]
There are also broken link sin the footer, "Found content that needs an update? You can [suggest content changes] (https://github.com/truenas/documentation/edit/master/SCALE/GettingStarted/Migrate/MigratingFromCORE.md) directly! To request changes to this content, click the Feedback button."

- the "suggest content changes" link redirects to a 404 page on this repository
- the "Feedback button" can not be found anywhere on the page

**Comment by g33z** [comment]
It feels like I've only come here to rant on your documentation... :sweat_smile:  
That is not the case, I really like it and I only want to make it better since I am convinced by TrueNAS's idea and its capabilities.
Thanks for being here and doing your stuff, good people :wave: <3

**Comment by Mrt134** [comment]
@g33z thanks for the PR and the feedback! For the broken links, I'll investigate what's happening and see why they're not pointing to the right locations. For the Feedback button, I want to confirm that you cannot see the feedback button on the side of the screen?
image

**Comment by g33z** [comment]
Whoopsie, yes the feedback button on the right hand side is visible once you turn the adblocker (uBlock origin) off. ;)
Thanks for the heads up.

**Comment by Mrt134** [comment]
No problem! I've addressed the other issues in https://github.com/truenas/documentation/pull/1923 and will go ahead close this PR. Thanks again for finding the issues and reporting them!

**Pull request closed without merging**
