### PR TITLE
DOCS-3827: deploying truenas vm in esxi environment

### PR DESCRIPTION
**Pull request by micjohnson777**
Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

### CODE REVIEW

**Review by pkgdemon — DISMISSED** [review]
In the following screenshot static/images/VMWareESXi/EditSettingsForTruenas1.png I would recommend to retake it with memory set to 32GB instead of 32768MB.  People are used to seeing memory values in terms of GB instead of MB these days.  It's the standard to see memory in GB.

**Comment by micjohnson777** [comment]
> In the following screenshot static/images/VMWareESXi/EditSettingsForTruenas1.png I would recommend to retake it with memory set to 32GB instead of 32768MB. People are used to seeing memory values in terms of GB instead of MB these days. It's the standard to see memory in GB.

Change made but not yet committed. Will make the next commit after all suggested changes are made.

**Comment by faRMerMcTechy** [comment]
This procedure works on my lab environment.

Where it says "you can click add hard disk again to add more hard drives" it may be useful to suggest why.

The first hard disk will be the boot/os drive to install TrueNAS on, additional disks would be used for storage pools on the TrueNAS VM.

**Comment by Mrt134** [comment]
Surge.sh instability, but build test passed. Approved for merge.

**Pull request merged**
